export type Locale = "uk" | "en";

export const dict = {
  uk: {
    brand: "ЯСТРУБ",
    tagline: "Тренувальний центр",
    hero_pre: "Тренувальний Центр",
    hero_brand: "ЯСТРУБ",
    hero_post: "",
    hero_sub: "Обери зброю, інструктора, програму і тренуйся з кращими.",
    hero_cert: "Сертифікат після проходження курсів.",
    lead_q1a: "Хочете записатися на тренування",
    lead_q1b: "зі зброєю",
    lead_desc1: "Залиште номер телефону —",
    lead_desc2: "з Вами зв'яжуться за декілька хвилин",
    lead_phone_ph: "Ваш номер телефону",
    lead_send: "Надіслати",
    lead_sending: "Надсилаємо...",
    lead_success: "Очікуйте на дзвінок!",
    lead_error: "Не вдалося надіслати. Перевірте номер і спробуйте ще раз.",
    step_course: "1. Обери курс",
    step_instructor: "2. Обери інструктора",
    step_program: "3. Програма тренінгу",
    step_register: "4. Реєстрація та оплата",
    level: "Рівень",
    duration: "Тривалість",
    price: "Вартість",
    uah: "грн",
    choose: "Обрати",
    chosen: "Обрано",
    back: "Назад",
    next: "Далі",
    instructors_for: "Інструктори курсу",
    instructor_more: "Ознайомитись з інструктором",
    inst_resume: "Резюме",
    inst_videos: "Відео з тренувань",
    inst_no_videos: "Відео з'являться незабаром.",
    inst_back_courses: "← До курсів",
    specialization: "Спеціалізація",
    program_title: "Зміст курсу (оглавлення)",
    total: "Разом до сплати",
    register_title: "Реєстрація",
    full_name: "ПІБ (як у сертифікаті)",
    email: "Email",
    phone: "Телефон",
    tg: "Telegram (@username)",
    consent: "Погоджуюсь на обробку персональних даних",
    pay: "Зареєструватися та сплатити",
    level_beginner: "Початковий",
    level_intermediate: "Середній",
    level_advanced: "Просунутий",
    pay_title: "Оплата курсу",
    pay_jar_hint:
      "Натисніть кнопку — відкриється банка monobank. Після оплати натисніть «Я оплатив», доступ активує адміністратор.",
    open_jar: "Сплатити через банку monobank",
    paid_btn: "Я оплатив(ла)",
    bot_title: "Доступ через Telegram-бот",
    bot_hint: "Сертифікат по QR-коду буде доступний після проходження курсу.",
    open_bot: "Відкрити Telegram-бот",
    done_title: "Готово!",
    done_hint: "Після підтвердження оплати ви отримаєте доступ у боті.",
    support: "Підтримка",
    err_generic: "Сталася помилка. Спробуйте ще раз.",
    err_consent: "Потрібна згода на обробку даних.",
    lang: "EN",
  },
  en: {
    brand: "YASTRUB",
    tagline: "Training center",
    hero_pre: "",
    hero_brand: "YASTRUB",
    hero_post: "Training Center",
    hero_sub: "Choose a weapon, an instructor, a program — and train with the best.",
    hero_cert: "Certificate upon course completion.",
    lead_q1a: "Want to sign up for training",
    lead_q1b: "with firearms",
    lead_desc1: "Leave your phone number —",
    lead_desc2: "we'll call you back within minutes",
    lead_phone_ph: "Your phone number",
    lead_send: "Send",
    lead_sending: "Sending...",
    lead_success: "Expect a call!",
    lead_error: "Couldn't send. Check the number and try again.",
    step_course: "1. Choose a course",
    step_instructor: "2. Choose an instructor",
    step_program: "3. Training program",
    step_register: "4. Registration & payment",
    level: "Level",
    duration: "Duration",
    price: "Price",
    uah: "UAH",
    choose: "Choose",
    chosen: "Chosen",
    back: "Back",
    next: "Next",
    instructors_for: "Course instructors",
    instructor_more: "About the instructor",
    inst_resume: "Resume",
    inst_videos: "Training videos",
    inst_no_videos: "Videos coming soon.",
    inst_back_courses: "← Back to courses",
    specialization: "Specialization",
    program_title: "Course contents (syllabus)",
    total: "Total due",
    register_title: "Registration",
    full_name: "Full name (as on certificate)",
    email: "Email",
    phone: "Phone",
    tg: "Telegram (@username)",
    consent: "I consent to personal data processing",
    pay: "Register & pay",
    level_beginner: "Beginner",
    level_intermediate: "Intermediate",
    level_advanced: "Advanced",
    pay_title: "Course payment",
    pay_jar_hint:
      "Tap the button — the monobank jar opens. After paying, tap “I have paid”; an admin activates access.",
    open_jar: "Pay via monobank jar",
    paid_btn: "I have paid",
    bot_title: "Access via Telegram bot",
    bot_hint: "Your QR-code certificate will be available after completing the course.",
    open_bot: "Open Telegram bot",
    done_title: "Done!",
    done_hint: "After payment confirmation you'll get access in the bot.",
    support: "Support",
    err_generic: "Something went wrong. Please try again.",
    err_consent: "Data-processing consent is required.",
    lang: "UA",
  },
} as const;

// Ключи берём из украинского словаря, значения — строки (обе локали совместимы).
export type Dict = { [K in keyof (typeof dict)["uk"]]: string };
